version: 2
updates:
  - package-ecosystem: pip 
    directory: "/install"
    target-branch: "develop"
    schedule:
      interval: "daily"
      
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
