repos:
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: .*dataset/.*|
                  (?x)(
                         ^config/local_ti_files/own_malicious_JA3.csv$|
                          .*test.* |
                         .*\.md$
                  )
