name: CI-production

on:
  push:
    branches:
    - 'master'
    - '!develop'
  pull_request:
    branches:
      - 'alya/have_separate_workflows_for_differemt_docker_imgs'

jobs:
  build_and_push_dependency_image:
    runs-on: ubuntu-latest
    steps:
    # clone slips and checkout branch
    - uses: actions/checkout@v3
      with:
        ref: 'master'

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: stratosphereips
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push latest dependency image
      id: docker_build_dependency_image
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: ./docker/dependency-image/Dockerfile
        tags: stratosphereips/slips_dependencies_TEST:latest
        push: true
