name: CI-production-publishing-dependency-image

on:
  push:
    branches:
    - 'master'
    - '!develop'

jobs:
  build_and_push_dependency_image:
    runs-on: ubuntu-latest
    steps:
    # clone slips and checkout branch
    - uses: actions/checkout@v4
      with:
        ref: 'master'

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: stratosphereips
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push latest dependency image
      id: docker_build_dependency_image
      uses: docker/build-push-action@v6
      with:
        context: ./
        file: ./docker/dependency-image/Dockerfile
        tags: stratosphereips/slips_dependencies:latest
        push: true
